# Generated by Django 3.1.1 on 2020-09-28 12:21

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(help_text='Vendos vendodhjen tuaj', max_length=100),
        ),
    ]
