# Generated by Django 3.1.1 on 2020-09-28 13:43

from django.db import migrations, models
import users.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200928_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, upload_to=users.utils.utils.user_directory_path_logo),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
