# Generated by Django 3.1.1 on 2020-09-28 13:52

from django.db import migrations, models
import users.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200928_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo e kompanise', upload_to=users.utils.utils.user_directory_path_logo),
        ),
    ]
