# Generated by Django 3.1.1 on 2020-09-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(blank=True, max_length=20, null=True)),
                ('currency_tag', models.CharField(max_length=4)),
                ('currency_symbol', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drivetrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivetrain_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_option_name', models.CharField(max_length=40)),
                ('header_option_tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=50)),
                ('make_logo', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_option_name', models.CharField(max_length=40)),
                ('search_option_tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_type', models.CharField(default=None, max_length=255, null=True)),
                ('engine_type', models.CharField(max_length=50)),
                ('production_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('exterior_color', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.body')),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.condition')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.currency')),
                ('door_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.door')),
                ('drivetrain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.drivetrain')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fuel')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.model')),
                ('seating_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.seatingcap')),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.seller')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=60)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleHighlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_name', models.CharField(max_length=60)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicletype'),
        ),
    ]
