# Generated by Django 3.1.1 on 2020-09-03 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trim',
            name='model_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.model'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle'),
        ),
        migrations.AddField(
            model_name='model',
            name='make_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.make'),
        ),
    ]
