# Generated by Django 3.1.1 on 2020-09-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200903_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='exterior_color',
        ),
    ]
