# Generated by Django 3.1.1 on 2020-09-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_vehicle_engine_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderSearch',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='make_id',
            new_name='make',
        ),
        migrations.RemoveField(
            model_name='cylinder',
            name='model',
        ),
        migrations.DeleteModel(
            name='Trim',
        ),
    ]
