# Generated by Django 3.1.1 on 2020-09-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_engine_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
