# Generated by Django 3.1.1 on 2020-09-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicletype'),
            preserve_default=False,
        ),
    ]
