# Generated by Django 3.1.1 on 2020-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_body_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
