# Generated by Django 3.1.1 on 2020-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200910_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
