# Generated by Django 3.1.1 on 2020-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_condition_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='extra_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
