# Generated by Django 3.1.1 on 2020-09-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_vehicle_extra_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuroToLek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.FloatField()),
            ],
        ),
    ]
