# Generated by Django 3.1.1 on 2020-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_eurotolek'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
